### ISSUE TITLE
The comments of CNN structure does not match codes

### ISSUE THREAD

**Issue by jxnclzl** [ardianumam/BanknotesRecognition#1]
The structure of your CNN  characters classifier：
# Second convolutional layer -- maps 32 feature maps to 64.
depth2 = 32
  W_conv2 = weight_variable([5, 5, depth1, depth2])
  b_conv2 = bias_variable([depth2])
  h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2) + b_conv2)

depth2= 32，but your comment said“ 64”. please tell me why ,Thank you very much！

**Comment by ardianumam** [comment]
Oh, I changed the network but forgot to update the comment. The right one is 32, as also written in [the paper](https://ieeexplore.ieee.org/document/8698683).
